### ISSUE TITLE
docker.sock persistent connection closed

### ISSUE THREAD

**Issue by LMAdrien** [dcylabs/albatros#3]
Hello,

I have this persistent problem. I tried several things without success. I do not know if this is related but mobile was in error on authentication.

[DOCKER] - Following error occured when trying to make request to Docker endpoint /var/run/docker.sock : persistent connection closed

thank you and that's good job.

**Comment by dcylabs** [comment]
Hello, 

What is your configuration ? (docker version and do you use it behind a proxy like HAProxy) 
The login error is not related to the docker sock, its an albatros issue so, when you say you're using mobile you mean web access from mobile or you use the albatros android app ? 

I will try to reproduce and fix it ASAP :)

**Comment by LMAdrien** [comment]
I use jwilder/nginx-proxy and docker version 1.6.2, build 7c8fca2. 
The proxy front-end use SSL but not backend.

My docker-compose:
albatros:
  image: dcylabs/albatros:(I tried different version)
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  expose:
    - 80
  environment:
    - VIRTUAL_HOST=fqdn (for proxy)
    - ACCOUNTS=username:$$password$$
    - SECRET=mysecret

And the authentication fail from albatros android app. 
Thank you

**Comment by dcylabs** [comment]
Finally found what was going wrong ! 
This is due to the jwilder/nginx-proxy usage, to get it working you should add following line in your [VHOST Configuration](https://github.com/jwilder/nginx-proxy#per-virtual_host)  :
`proxy_set_header Connection ""`

But there is still an issue with the proxying of console websockets (on nginx-proxy side so). If you only use the android app, that's okay as it doesnt use console WS. But if you need, I recommend using HAProxy  ( Im not very familiar with nginx proxying )

Can you confirm me that it is solved ?

**Comment by LMAdrien** [comment]
Yes, thank you for your help. Problem solved ! 
I will also start working with haproxy ;) .

P.S: Also after update docker version 1.6.2 to 1.12.1 all features are available.  

Adrien

**Comment by 3Nigma** [comment]
Thank you for the hint on how to solve this!

I arrived to this issue while running a Portrainer (former docker-ui project) continer where I got the same behavior when using with nginx-proxy.

I just wanted to give a heads-up to whoever reaches this while trying to make Portrainer work behind a nginx-proxy container.
